# -*- coding: utf-8 -*-
"""colab.upynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1g71IMCQ0ly6z28hYO2QasWjSZgVVKSmR
"""

n1 = float(input("Primeira nota"))
n2 = float(input("Segunda nota"))
n3 = float(input("Terceira nota"))

media = (n1+n2+n3)/3

if(media >=7):
    situaçao = 'Aprovado'
elif(media  <=4):
    situaçao = 'Reprovado'
else:
    situaçao = 'prova final'

print(f'o aluno foi {situaçao}, com a media {media:.2f}')